## TensorFlow tutorial

Learn to:

    - Initialize variables
    - Start own session
    - Train algorithms
    - Implement NN

In [1]:
import math
import numpy as np
import h5py
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.python.framework import ops
from tf_utils import load_dataset, random_mini_batches, convert_to_one_hot, predict

%matplotlib inline
np.random.seed(1)

Writing and running programs in TF has the following steps:

    - Create Tensors that aren't yet executed/evaluated
    - Write operations between those Tensors
    - Initialize your tensors
    - Create Session
    - Run the session
    
Remember to ** initialize the variables, create a session and then run operations inside the session. **

***Placeholder:*** Placeholder is an object whose value you can specify only later. To specify values for placeholder, one can pass in values by using "feed dictionary" 

In [9]:
y_hat = tf.constant(36, name='y_hat')            # Define y_hat constant. Set to 36.
y = tf.constant(39, name='y')                    # Define y. Set to 39

loss = tf.Variable((y - y_hat)**2, name='loss')  # Create a variable for the loss

init = tf.global_variables_initializer()         # When init is run later (session.run(init)),
                                                 # the loss variable will be initialized and ready to be computed
sess= tf.Session()
sess.run(init)
print(sess.run(loss))

9


In [10]:
x = tf.placeholder(tf.int64, name = 'x')
print(sess.run(2**x, feed_dict = {x: 3}))
sess.close()

8


** 1. Linear Function: **

We will be computing Y = WX + b, where W, X and b are drawn from a random normal distribution.

shape_W = (4,3)

shape_X = (3,1)

shape_b = (4,1)

In [11]:
def linear_function():
    
    np.random.seed(1)
    
    X = tf.constant(np.random.randn(3,1), name = 'X')
    W = tf.constant(np.random.randn(4,3), name = 'W')
    b = tf.constant(np.random.randn(4,1), name = 'b')
    Y = tf.add(tf.matmul(W,X), b)
    
    
    sess = tf.Session()
    result = sess.run(Y)
    
    sess.close()
    
    return result

print( "result = " + str(linear_function()))

result = [[-2.15657382]
 [ 2.95891446]
 [-1.08926781]
 [-0.84538042]]


** 2. Computing Sigmoid **

Done using placeholder variable. We should use feed dictionary to pass in input z.

- Create a placeholder x
- Define operations needed to compute the sigmoid using tf.sigmoid
- Run session

In [13]:
def sigmoid(z):
    
    x = tf.placeholder(tf.float32, name = 'x')
    sigmoid = tf.sigmoid(x)
    
    sess = tf.Session()
    result = sess.run(sigmoid, feed_dict = {x:z})
    sess.close()
    
    return result

print("sigmoid(2) = "+ str(sigmoid(2)))
print("sigmoid(12) = "+ str(sigmoid(12)))

sigmoid(2) = 0.880797
sigmoid(12) = 0.999994


** 3. Cost Computation **

To compute cross entropy loss in TF, we use: tf.nn.sigmoid_cross_entropy_with_logits(logits = ..., labels = ...)

- Input z
- Compute sigmoid of z to get a
- Compute cross entropy K
- call the above function to do all this

In [14]:
def cost(logits, labels):
    
    z = tf.placeholder(tf.float32, name='z')
    y = tf.placeholder(tf.float32, name='y')
    
    cost = tf.nn.sigmoid_cross_entropy_with_logits(logits = z, labels = y)
    
    sess = tf.Session()
    result = sess.run(cost, feed_dict={z:logits, y: labels})
    
    sess.close()
    
    return result


logits = sigmoid(np.array([0.2,0.4,0.7,0.9]))
cost = cost(logits, np.array([0,0,1,1]))
print ("cost = " + str(cost))

cost = [ 1.00538719  1.03664088  0.41385433  0.39956614]


** 4. Using One Hot Encodings: **

This is called a "one hot" encoding, because in the converted representation exactly one element of each column is "hot" (meaning set to 1). To do this conversion in numpy, you might have to write a few lines of code. In tensorflow, you can use one line of code:

    - tf.one_hot(labels, depth, axis)


In [21]:
def one_hot_matrix(labels, C):
    
    C = tf.constant(C, name='C')
    one_hot_matrix = tf.one_hot(indices=labels, depth=C, axis=0)
    sess = tf.Session()
    one_hot = sess.run(one_hot_matrix)
    sess.close()
    
    return one_hot

labels = np.array([1,2,3,0,2,1])
one_hot = one_hot_matrix(labels, C = 3)
print ("one_hot = \n" + str(one_hot))

one_hot = 
[[ 0.  0.  0.  1.  0.  0.]
 [ 1.  0.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  1.  0.]]


** 4. Initialize with zeros and ones **

- tf.zeros()
- tf.ones()

In [22]:
def ones(shape):
    
    ones = tf.ones(shape)
    sess = tf.Session()
    ones = sess.run(ones)
    
    sess.close()
    
    return ones

print ("ones = " + str(ones([3])))


ones = [ 1.  1.  1.]




## Building Neural Network with TensorFlow

There are two parts to implement this tf model:

- Create the computation graph
- Run the graph

    ** Problem Statement:** SIGNS Dataset
    

Training set: 1080 pictues
Test set : 120