In [2]:
import math
import numpy as np
import h5py
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.python.framework import ops
from tf_utils import load_dataset, random_mini_batches, convert_to_one_hot, predict

%matplotlib inline
np.random.seed(1)

In [6]:
y_hat = tf.constant(36, name = 'y_hat')
y = tf.constant(39, name = 'y')

loss = tf.Variable((y-y_hat)**2, name = 'loss')

init = tf.global_variables_initializer()

with tf.Session() as session:
    session.run(init)
    print(session.run(loss))

9


Tensor("Mul:0", shape=(), dtype=int32)
As expected, you will not see 20! You got a tensor saying that the result is a tensor that does not have the shape attribute, and is of type "int32". All you did was put in the 'computation graph', but you have not run this computation yet. In order to actually multiply the two numbers, you will have to create a session and run it.

In [7]:
a = tf.constant(2)
b = tf.constant(10)
c = tf.multiply(a,b)
print(c)

Tensor("Mul:0", shape=(), dtype=int32)


In [8]:
sess = tf.Session()
print(sess.run(c))

20


### Linear Function

Y = WX +b

X = tf.constat(np.random.randn(3,1), name = "X")

tf.matmul - Matrix multiplication
tf.add() - Add





In [11]:
def linear_function():
    
    W = np.random.randn(4,3)
    X = np.random.randn(3,1)
    b = np.random.randn(4,1)
    Y = tf.add(tf.matmul(W,X),b)
    
    sess = tf.Session()
    result = sess.run(Y)
    
    sess.close()
    
    return result

In [12]:
print(str(linear_function()))

[[-1.98748544]
 [-2.76826248]
 [-0.78635415]
 [-2.77463846]]


### Implementing Sigmoid function: 

tf.placeholder(tf.float32, name = "...")

tf.sigmoid(...)

sess.run(..., feed_dict = {x: z})

In [16]:
def sigmoid(z):
    
    x = tf.placeholder(tf.float32, name = "x")
    
    sigmoid = tf.sigmoid(x)
    
    with tf.Session() as sess:
        result = sess.run(sigmoid, feed_dict = {x:z})
    
    return result

print(str(sigmoid(0)))

0.5


### Computing Cost

tf.nn.sigmoid_cross_entropy_with_logits(logits = ...,  labels = ...)


In [17]:
def cost(logits1, labels1):
    
    z = tf.placeholder(tf.float32, name = "z")
    y = tf.placeholder(tf.float32, name = "y")
    
    cost = tf.nn.sigmoid_cross_entropy_with_logits(logits= z,labels=y)
    
    with tf.Session() as sess:
        c = sess.run(cost, feed_dict = {z: logits1, y: labels1})
        
    return c

logits = sigmoid(np.array([0.2,0.4,0.7,0.9]))
cost = cost(logits, np.array([0,0,1,1]))
print(str(cost))
        
    
    

[1.0053872  1.0366409  0.41385433 0.39956614]


### One hot matrix


tf.one_hot(labels, depth, axis)



In [26]:
def one_hot_matrix(labels, C):
    
    C = tf.constant(C, name = "C")
    
    one_hot_matrix = tf.one_hot(indices = labels, depth = C, axis = 0)
    
    sess = tf.Session()
    one_hot = sess.run(one_hot_matrix)
    sess.close()
    
    return one_hot


labels = np.array([1,2,4,5,2,1])
one_hot = one_hot_matrix(labels, C=4)
print ("one_hot = \n" + str(one_hot))

one_hot = 
[[0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]
